///Import Statements
import javax.swing.*;//provides classes for building GUI
import java.awt.*;//provides classes for managing GUI components
import java.awt.event.*;//provides classes and interfaces for handling events generated by user interactions
import java.sql.*;//provides classes and interfaces for accessing and processing data stored in a database
public class TaskManager extends JFrame implements ActionListener {

    //Create assests
    private JButton addTask, viewAll;
    private JTextField taskAdder;
    private JPanel mainPanel;

    public TaskManager(){//Constructor for 'TaskManager' class
        setTitle("Task Manager");//sets title of GUI window
        setSize(500,200);//define size of GUI window
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//sets default close operation for the window

        addTask = new JButton("Add Task"); //creates JButton object
        viewAll = new JButton("View All"); //creates JButton object
        taskAdder = new JTextField(20);//create text feild
        //20 is the width of the text feild

        addTask.addActionListener(this);
        //Adds ActionLister to the 'addTask' object

        viewAll.addActionListener(this);
        //Adds ActionLister to the 'viewAll' object

        //Create button panel to arrange buttons on grid
        JPanel buttonPanel = new JPanel(new GridLayout(1, 2));
        //sets layout to 'GridLayout' w/ 1 row + 2 columns
        //'GridLayout' --> components added to panel will be arranged in grid, specified # of rows and columns

        //Create input panel for user input + label
        JPanel inputPanel = new JPanel();
        inputPanel.add(new JLabel("Add Task:"));
        inputPanel.add(taskAdder);

        buttonPanel.add(addTask);//adds 'searchButton' component to 'buttonPanel
        //search button will be displayed in button panel according to layout defined by 'GridLayout'
        buttonPanel.add(viewAll);//adds 'inputButton' component to 'buttonPanel

        mainPanel = new JPanel(new BorderLayout());
        //'BorderLayout' --> layout manager, divides container into 5 regions: N, S, E, W, Center
        //               --> Each region can only contain one component (compo. @ N positioned at top of container, etc..)
        //               --> found in 'java.swing'

        mainPanel.add(new JLabel("Please Input Task Below:"), BorderLayout.NORTH);
        // mainPanel.add(new JLabel("Please Input Task:"), BorderLayout.NORTH);



        JTextField TaskAdder = new JTextField(20);//Create Text Feild
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);//Place button panel at bottom of window
        mainPanel.add(inputPanel, BorderLayout.CENTER);


        add(mainPanel); // Add main panel to the frame
        setVisible(true);

    }//TaskManager Constructor
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == addTask) {
            String task = taskAdder.getText();
            if (!task.isEmpty()) {
                insertTask(task);
            } else {
                JOptionPane.showMessageDialog(this, "Task cannot be empty!");
            }
        } else if (e.getSource() == viewAll) {
            showAllTasks();
        }
    }

    //Method for task insertion
    private void insertTask(String task) {
        try {
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/mukuwa.baffoe/Documents/Database3.accdb");
            String query = "INSERT INTO ToDo (TaskInput) VALUES (?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, task);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Task added successfully!");
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    //////////////////////////////////////////////////////////////////////////////////////////////////
    private void showAllTasks() {
        JFrame viewFrame = new JFrame("All Tasks");
        viewFrame.setSize(400, 300);
        viewFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JTextArea tasksArea = new JTextArea();
        tasksArea.setEditable(false);

        try {
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/mukuwa.baffoe/Documents/Database3.accdb");
            String query = "SELECT TaskInput FROM ToDo";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                tasksArea.append(rs.getString("TaskInput") + "\n");
            }

            con.close();
        } catch (SQLException ex) {
            tasksArea.setText("Error: " + ex.getMessage());
        }

        viewFrame.add(new JScrollPane(tasksArea));
        viewFrame.setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(TaskManager::new);
    }
}
